version: '3'

services: 
  app:
    image: adalbertorsilvajr/backend-ammo-challenge:latest
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=junior
    ports:
      - 3001:3001
    depends_on: 
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=junior
      - POSTGRES_USER=postgres 
    restart: always
    ports: 
      - 5433:5432
  front:
    image: adalbertorsilvajr/frontend-ammo-challenge-nginx:latest
    ports: 
      - 8080:80
    depends_on: 
      - app